[workspace]
resolver = "2"
members = [
    "libs/sectools-common",
    "tools/subnet-scanner",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/flaviomilan/sectools"
authors = ["Flavio Milan"]
